name: GitHub Slug Action

on:
  push

jobs:
  check-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Inject enhanced GitHub environment variables
        uses: rlespinasse/github-slug-action@v5
